// <auto-generated />
using System;
using BancoWeb.Model.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BancoWeb.Migrations
{
    [DbContext(typeof(DbConn))]
    partial class DbConnModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BancoWeb.Model.Entity.Agencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("agenciaName");

                    b.HasKey("id");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("BancoWeb.Model.Entity.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("clientName");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BancoWeb.Model.Entity.Conta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("agenciaid");

                    b.Property<int?>("clienteid");

                    b.Property<double>("saldo");

                    b.HasKey("id");

                    b.HasIndex("agenciaid");

                    b.HasIndex("clienteid");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("BancoWeb.Model.Entity.Conta", b =>
                {
                    b.HasOne("BancoWeb.Model.Entity.Agencia", "agencia")
                        .WithMany("listaConta")
                        .HasForeignKey("agenciaid");

                    b.HasOne("BancoWeb.Model.Entity.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
